import org.gradle.plugins.ide.eclipse.model.SourceFolder;

plugins {
    id 'eclipse'
}

tasks.clean {
    doFirst {
        new File("${project.projectDir}/build").deleteDir()
        new File("${project.projectDir}/bin").deleteDir()
        new File("${project.projectDir}/.settings").deleteDir()
        new File("${project.projectDir}/.project").delete()
        new File("${project.projectDir}/.classpath").delete()
    }
}

eclipse {
    classpath {
        file {
            whenMerged {
                entries = entries.findAll { it instanceof SourceFolder ? ((SourceFolder)it).output != "bin/test" : true }

                // MODULES
                /*
                def modules = extension.modules

                modules += ['javafx', 'ntro']

                entries.each { entry ->

                    if(entry instanceof org.gradle.plugins.ide.eclipse.model.AbstractClasspathEntry) {

                        def classpathEntry = (org.gradle.plugins.ide.eclipse.model.AbstractClasspathEntry) entry;

                        if(modules.any{moduleName -> classpathEntry.path.contains(moduleName)}){

                            classpathEntry.getEntryAttributes().put("module","true")
                        }
                    }
                }*/
            }
        }
    }
}

tasks.eclipse.dependsOn(build)
